exclude: >
    (?x)(
        LICENSE$|
        \.snap$|
        \.map$|
        \.map\.js$|
        ^tests/fixtures/
    )

repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      types: [python]
      exclude: (migrations/)
      args:
        - "--line-length=160"
        - "--target-version=py27"
-   repo: local
    hooks:
    # - id: isort
    #   name: isort
    #   entry: isort
    #   language: python
    #   types: [python]
    #   args:
    #     - "--multi-line=3"
    #     - "--trailing-comma"
    #     - "--force-grid-wrap=0"
    #     - "--combine-as"
    #     - "--line-width=160"
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      files: \.py$
      log_file: '.artifacts/flake8.pycodestyle.log'
      additional_dependencies:
       - git+git://github.com/Convertize/convertize-flake8@master#egg=convertize-flake8
      args:
        - "--max-line-length=160"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"
        - "--ignore=E211,E999,F401,F821,W503"
-   repo: https://github.com/sirosen/check-jsonschema
    rev: 0.3.0
    hooks:
    - id: check-github-actions
    - id: check-github-workflows
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-symlinks
    - id: end-of-file-fixer
      exclude_types: [svg]
    - id: trailing-whitespace
      exclude_types: [svg]
    - id: debug-statements
